FROM jboss/wildfly
ADD elasticwow.war /opt/jboss/wildfly/standalone/deployments/

#RUN mkdir /opt/wowelastic
#RUN mkdir /opt/wowelastic/conf

ADD wowelastic.properties /opt/wowelastic/conf/wowelastic.properties
